export enum ArticleId {
    agilityRocks = 'agility-rocks',
    leakedApiKey = 'leaked-api-key',
    meaningOfLife = 'meaning-of-life',
    fourCoinChallenge = 'four-coin-challenge',
    progressiveWebApps = 'progressive-web-apps',
    existentialInjustice = 'existential-injustice',
    subscribersList = 'subscribers-list',
    kanbanGoalsTracking = 'kanban-goals-tracking',
    trecember = 'trecember',
    webDevOnSteroidsI = 'web-dev-on-steroids-i',
    webDevOnSteroidsII = 'web-dev-on-steroids-ii',
    sudokuGeneration = 'sudoku-generation',
    persuasionInPictures = 'persuasion-in-pictures',
    stadiaPlatform = 'stadia-platform',
    webBadDecisions = 'web-bad-decisions',
    linearGradient = 'linear-gradient',
    expressOnGoogleCloud = 'express-on-google-cloud',
    npmPackagesDevelopment = 'npm-packages-development'
}
